config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create destroy update] do
        resources :answers, only: %i[index show create destroy update], shallow: true
      end
    end
  end

  resources :users do
    get :rewards, on: :member
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: %i[create]
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: %i[index, show], shallow: true do
      patch :best_answer, on: :member
    end
    resources :subscribes, shallow: true, only: %i[create destroy]
  end

  resources :files, only: :destroy

  resources :links, only: :destroy

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable
  
  has_one :reward, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  belongs_to :user
  has_many :subscribes, dependent: :destroy
  has_many :subscribers, through: :subscribes

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank
  
  validates :title, :body, presence: true

  after_create :calculate_reputation

  scope :today, -> { where("DATE(created_at) = ? ", Date.today) }

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :set_question, only: %i[answers show destroy update]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer, root: "questions"
  end

  def show
    render json: @question, serializer: QuestionSerializer
  end

  def create
    @question = current_resource_owner.questions.build(question_params)
    
    if @question.save
      render json: @question, serializer: QuestionSerializer
    end
  end

  def update
    if @question.update(question_params)
      render json: @question, serializer: QuestionSerializer
    else
      render json: { message: 'error update', status: 422 }
    end
  end

  def destroy
    @question.destroy
    render json: { message: "question deleted", status: 200 }
  end
  private

  def set_question
    @question ||= Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: [:name, :url], reward_attributes: [:title, :img_url])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  after_action :publish_question, only: %i[create]
  after_action :set_question_gon, only: %i[show]

  include Voted

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer ||= question.answers.new
    @answer.links.new
    @comment = @question.comments.build(user: current_user)
    @subscribe = @question.subscribes.find_by(subscriber: current_user)
  end

  def new
    question.links.new
    question.build_reward
  end

  def edit; end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    question.update(question_params)
  end

  def destroy
    if current_user.author?(question)
      question.destroy 
      redirect_to questions_path, notice: 'Your question was successfully deleted!'
    else
      redirect_to questions_path, notice: 'Your question was not deleted!'
    end
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  helper_method :question

  def question_params
    params.require(:question).permit(:title, :body, 
                                      files: [], links_attributes: [:name, :url],
                                      reward_attributes: [:title, :image_url])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast('questions',{ question: @question, user_id: current_user.id })
  end

  def set_question_gon
    gon.question_id = question.id
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
.question-errors
  = render 'shared/errors', resource: @question

= form_with model: question, local: false do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true
    
  #links
    = f.fields_for :links do |link|
    .add-links
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
  #reward
    = f.fields_for :reward do |r|
      = render 'shared/reward_fields', r: r

  p= f.submit 'Ask'

app/views/questions/_question.html.slim
tr
  td= ("#{question.title}")
  = ' | '
  td= ("#{question.body}")

  div class="vote-question-rating"
    = render 'shared/vote', votable: question

  .links
    p Links:
    ul 
      -question.links.each do |link|
        div id="link_#{link.id}"
          .link-errors
            = render 'shared/errors', resource: link
          - if link.gist?
            script src="#{link.url}.js"
          - else
          = link_to link.name, link.url
          - if current_user&.author?(question)
            = ' | '
            = link_to 'Delete link', link_path(link), method: :delete, remote: true

  - if current_user&.subscriber_of?(question)
    p= button_to "Unsubscribe", subscribe_path(@subscribe), method: :delete
  - else
    p= button_to "Subscribe", question_subscribes_path(question), method: :post

  - if question.reward.present?
    div class="reward"
      = "Reward:"
      img src=url_for(question.reward.image_url)
 
- if question.persisted?
  - if current_user&.author?(question)
    p= link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: question.id }

    -if question.files.attached?
      -question.files.each do |file|
        div id="file_#{file.id}"
          = link_to file.filename.to_s, url_for(file)
          - if current_user&.author?(question)
            = ' | '
            = link_to 'Delete file', file_path(file), method: :delete, remote: true
  
    = form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" }, local: false, data: { type: :json } do |f|
      p
        = f.label :title, 'Your question title'
        = f.text_field :title
      p
        = f.label :body, 'Your question body'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true
      #links
        = f.fields_for :links do |link|
        .add-links
          = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
      p= f.submit 'Save'

- if current_user&.author?(question)
  p= link_to 'Delete question', question_path(question), method: :delete, remote: true
  

app/views/questions/index.html.slim
.questions
  h3 Questions
  .question-errors
  = render @questions
  
- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
h3= 'Questions'

.questions
  .question data-id="#{question.id}"
    .question-errors
      = render @question
      = render "comments/comments", commentable: question
      = render "comments/form", commentable: question
      
h3= 'Answers'

.answers
  .answers-errors
  = render @question.answers

- if current_user.present?
  p= render 'answers/form'
  

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.questions').html('<%= j render @question %>');
<% end %>