config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => 'sidekiq'
  end

  use_doorkeeper
  devise_for :users
  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create destroy update] do
        resources :answers, only: %i[index show create destroy update], shallow: true
      end
    end
  end

  resources :users do
    get :rewards, on: :member
  end

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      delete :delete_vote
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: %i[create]
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :answers, concerns: %i[votable commentable], except: %i[index, show], shallow: true do
      patch :best_answer, on: :member
    end
    resources :subscribes, shallow: true, only: %i[create destroy]
  end

  resources :files, only: :destroy

  resources :links, only: :destroy

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable
  
  belongs_to :user
  belongs_to :question
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  
  validates :body, presence: true

  after_create :notificate_question_subscribers

  default_scope { order(best: :desc) }

  def make_best
    transaction do
    	question.answers.update_all(best: false)
    	update!(best: true)
      question.reward&.update!(user: user)
    end
  end

  private

  def notificate_question_subscribers
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  after_action :publish_answer, only: %i[create]
  after_action :set_answer_gon, only: %i[create]

  include Voted

  authorize_resource

  def show; end

  def new; end

  def edit; end

  def create
    @answer = question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save

    respond_to do |format|
      if @answer.save
        format.json { render json: @answer }
      else
        format.json do 
          render json: @answer.errors.full_messages, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    answer.update(answer_params) if current_user.author?(answer)
  end

  def destroy
    answer.destroy if current_user.author?(answer)
  end

  def best_answer
    answer.make_best if current_user.author?(question)
  end

  private

  def question
    @question ||= params[:question_id] ? Question.find(params[:question_id]) : answer.question
  end

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new
  end

  helper_method :question, :answer

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast("questions/#{params[:question_id]}/answers", answer: @answer, user_id: current_user.id)
  end

  def set_answer_gon
    gon.answer_id = answer.id
  end

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: %i[index create]
  before_action :set_answer, only: %i[show destroy update]

  authorize_resource

  def index
    @answers = @question.answers
    render json: @answers, each_serializer: AnswersSerializer, root: "answers"
  end

  def show
    render json: @answer, serializer: AnswerSerializer
  end

  def create
    @answer = current_resource_owner.answers.build(answer_params)
    @answer.question = @question
    
    if @answer.save
      render json: @answer, serializer: AnswerSerializer
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer, serializer: AnswerSerializer
    else
      render json: { message: 'error update', status: 422 }
    end
  end

  def destroy
    @answer.destroy
    render json: { message: "answer deleted", status: 200 }
  end

  private

  def set_question
    @question ||= Question.find(params[:question_id])
  end

  def set_answer
    @answer ||= Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div id="answer_#{answer.id}"
    - if answer.best
      p class="best-answer" Best answer

    p= answer.body
    
    div class="vote-answer-rating"
      = render 'shared/vote', votable: answer

    .links
      p Links:
      ul 
        -answer.links.each do |link|
            .link-errors
              = render 'shared/errors', resource: link
            - if link.gist?
              script src="#{link.url}.js"
            - else
            = link_to link.name, link.url
            - if current_user&.author?(answer)
              = ' | '
              = link_to 'Delete link', link_path(link), method: :delete, remote: true
    
    - if current_user&.author?(answer.question) && !answer.best
      p= link_to  'Choose as the best answer', best_answer_answer_path(answer), method: :patch, remote: true 
    - if current_user&.author?(answer)
      p= link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

      -if answer.files.attached?
        -answer.files.each do |file|
          div id="file_#{file.id}"
            = link_to file.filename.to_s, url_for(file)
            - if current_user&.author?(answer)
              = ' | '
              = link_to 'Delete file', file_path(file), method: :delete, remote: true

      = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, data: { type: :json } do |f|
        p
          = f.label :body, 'Your answer'
          = f.text_area :body
        p
          = f.label :files
          = f.file_field :files, multiple: true
        #links
          = f.fields_for :links do |link|
          .add-links
            = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
        p= f.submit 'Save'

      p= link_to 'Delete answer', answer_path(answer), method: :delete, remote: true

    = render "comments/comments", commentable: answer
    - if current_user
      - @comment = answer.comments.build(user: current_user)
      = render "comments/form", commentable: answer
          

app/views/answers/_form.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer

= form_with model: [question, @answer], class: 'new-answer', local: false, data: { type: :json } do |f|
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true 
  #links
    = f.fields_for :links do |link|
    .add-links
      = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
        
  p= f.submit 'Create answer'
  

app/views/answers/best_answer.js.erb
$("#answer_<%= @answer.id %>").html('<%= j render answer %>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$("#answer_<%= @answer.id %>").remove();

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render question.answers %>');
<% end %>